# Generated by Django 2.1.1 on 2018-09-09 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rivue', '0003_brands'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brands',
            new_name='Brand',
        ),
    ]
